import { describe, it, expect } from 'vitest';
import { sequenceRatio, stringRatio, matchingBlocks } from './similarity';

/**
 * Expected values generated by CPython's `difflib.SequenceMatcher(None, a, b).ratio()`.
 *
 * Fixed here rather than computed, because the point is to pin our numbers to
 * the reference implementation the spec names — a test that recomputed them
 * with our own code would agree with itself and prove nothing. Two thresholds
 * downstream (0.6 for scene openings, 0.7 for echoed summaries) were calibrated
 * against these exact semantics.
 */
const STRING_CASES: [string, string, number][] = [
  ['', '', 1.0],
  ['abc', 'abc', 1.0],
  ['abc', 'xyz', 0.0],
  ['the rain fell in sheets', 'the rain fell in curtains', 0.75],
  ['She opened the door.', 'She opened the window.', 0.857142857143],
  ['Kaelen woke before dawn.', 'Kaelen woke before the dawn broke.', 0.827586206897],
  ['A heavy sheet of corrugated plastic', 'heavy sheet of corrugated plastic rattled', 0.868421052632],
  ['qwertyuiop', 'poiuytrewq', 0.1],
  ['aaaa', 'aa', 0.666666666667],
  ['the quick brown fox', 'the quick brown fox jumps over', 0.775510204082],
  ['Rain hammered the tin roof.', 'Rain hammered the roof of tin.', 0.80701754386],
];

const WORD_CASES: [string[], string[], number][] = [
  [['the', 'rain', 'fell', 'in', 'sheets'], ['the', 'rain', 'fell', 'in', 'curtains'], 0.8],
  [['she', 'opened', 'the', 'door'], ['she', 'opened', 'the', 'window'], 0.75],
  [['a', 'b', 'c', 'd', 'e'], ['c', 'd', 'e', 'a', 'b'], 0.6],
];

describe('sequence similarity matches difflib.SequenceMatcher', () => {
  it.each(STRING_CASES)('stringRatio(%j, %j) === %f', (a, b, expected) => {
    expect(stringRatio(a, b)).toBeCloseTo(expected, 10);
  });

  it.each(WORD_CASES)('sequenceRatio over words', (a, b, expected) => {
    expect(sequenceRatio(a, b)).toBeCloseTo(expected, 10);
  });

  it('is symmetric enough for a threshold, and self-similarity is 1', () => {
    for (const [a] of STRING_CASES) expect(stringRatio(a, a)).toBe(1);
  });

  it('returns matching blocks in order, covering the common runs', () => {
    const blocks = matchingBlocks([...'abxcd'], [...'abycd']);
    expect(blocks.map((b) => [b.aStart, b.bStart, b.size])).toEqual([[0, 0, 2], [3, 3, 2]]);
  });

  it('handles one side empty without dividing by zero', () => {
    expect(stringRatio('', 'abc')).toBe(0);
    expect(stringRatio('abc', '')).toBe(0);
  });
});
