import type { Plugin } from 'vite';

/**
 * Emit a service worker that precaches the built app.
 *
 * Written here rather than taken from `vite-plugin-pwa`/Workbox, which is the
 * usual answer and would have been reasonable. Two reasons it is not used:
 * thirty transitive packages for what is sixty lines of cache handling, in a
 * repository that licence-audits its dependency tree; and, more importantly,
 * the update policy below is not Workbox's default and is the part that
 * actually matters here.
 *
 * **The update policy: the new version waits.** No `skipWaiting`, no
 * `clients.claim()`. A service worker that activates immediately swaps the
 * asset bundle under a page that is already running — and since the old page
 * fetches its worker and lazily-imported chunks by hashed URL, and a Pages
 * deploy removes the old hashes, that page can break mid-sentence. For a
 * writing app that is the wrong trade at any speed. So the new worker sits in
 * `waiting` until the writer chooses to reload, and the UI says so.
 *
 * It also keeps the cached app and the on-disk schema honest: `migrate()` moves
 * `user_version` forward permanently, so an old shell serving against a newly
 * migrated database is a genuine hazard rather than a cosmetic one. An update
 * the writer takes deliberately, all tabs at once, cannot land in that state.
 */
export function serviceWorker(): Plugin {
  let base = '/';
  return {
    name: 'lorescribe:service-worker',
    apply: 'build',
    configResolved(config) { base = config.base; },
    generateBundle(_options, bundle) {
      const assets = Object.keys(bundle)
        .filter((name) => !name.endsWith('.map'))
        .map((name) => base + name);
      // The shell and the things a first offline load needs that are not in the
      // bundle graph. index.html is listed by path, not by name, because that is
      // what a navigation actually requests.
      const precache = [
        base,
        base + 'manifest.webmanifest',
        base + 'icons/icon-192.png',
        base + 'icons/icon-512.png',
        base + 'icons/icon-maskable-512.png',
        ...assets,
      ];
      // One cache name per build. Changing any asset changes a hash, which
      // changes this string, which is what makes the browser install a new
      // worker at all.
      const version = hash(precache.join('\n'));

      this.emitFile({ type: 'asset', fileName: 'sw.js', source: swSource(precache, version, base) });
    },
  };
}

function hash(s: string): string {
  let h = 0x811c9dc5;
  for (let i = 0; i < s.length; i++) {
    h ^= s.charCodeAt(i);
    h = Math.imul(h, 0x01000193) >>> 0;
  }
  return h.toString(16).padStart(8, '0');
}

function swSource(precache: string[], version: string, base: string): string {
  return `/* Generated by tools/swPlugin.ts — do not edit. */
const CACHE = 'lorescribe-${version}';
const PRECACHE = ${JSON.stringify(precache, null, 2)};
const SHELL = ${JSON.stringify(base)};

// ignoreVary is not a shortcut. The preview and Pages servers send
// \`Vary: Origin\` on static assets; the precache stored those responses against
// a request with no Origin header, and a module script from the page sends one,
// so strict Vary matching misses EVERY asset and the app fails to load offline
// while the cache sits there full. The entries are immutable content-hashed
// files — the URL is the whole identity.
const MATCH = { ignoreVary: true };

self.addEventListener('install', (event) => {
  // Deliberately no skipWaiting: a new version waits for the writer to reload.
  event.waitUntil(caches.open(CACHE).then((c) => c.addAll(PRECACHE)));
});

self.addEventListener('activate', (event) => {
  event.waitUntil((async () => {
    for (const name of await caches.keys()) {
      if (name !== CACHE && name.startsWith('lorescribe-')) await caches.delete(name);
    }
    // Only once this worker is the active one — which, without skipWaiting,
    // means every tab of the old version has already gone.
    await self.clients.claim();
  })());
});

// The one message this worker takes, sent by the reload button in the UI.
self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') self.skipWaiting();
});

self.addEventListener('fetch', (event) => {
  const request = event.request;
  if (request.method !== 'GET') return;
  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return;

  // A navigation goes to the network first, so a deploy is noticed rather than
  // hidden behind a cached shell, and falls back to the cached shell offline.
  if (request.mode === 'navigate') {
    event.respondWith((async () => {
      try {
        return await fetch(request);
      } catch {
        return (await caches.match(SHELL, MATCH)) ?? Response.error();
      }
    })());
    return;
  }

  // Everything else is content-hashed or an icon: cache first, and fill the
  // cache on a miss so a lazily-loaded chunk is there next time offline.
  event.respondWith((async () => {
    const hit = await caches.match(request, MATCH);
    if (hit) return hit;
    const response = await fetch(request);
    if (response.ok && response.type === 'basic') {
      const cache = await caches.open(CACHE);
      await cache.put(request, response.clone());
    }
    return response;
  })());
});
`;
}
